### PR TITLE
Editor

### PR DESCRIPTION
**Pull request by mdcliner**
These changes reference #22

### CODE REVIEW

**Comment by mdalmazan** [comment]
Here is a [screenshot](https://screenshots.firefox.com/4BeyL6r2Ia92Sv3L/localhost) of the changes
@nithinsanjey

**Comment by nithinsanjey** [comment]
@mdalmazan I will check your code in local and approve your PR!

**Comment by uvsankar** [comment]
@mdalmazan  Can you squash all these commits. Just have two commits one for WYSIWYG editor and other for Dropcap. I'll do code review tomorrow.

Can we have a toggle switch for these two features. 

@nithinsanjey  @mdalmazan  We can  add as many features as we want. But we should give the users control over which UI feature should be enabled. Please share your thoughts on this.

**Comment by nithinsanjey** [comment]
In my opinion, toggle switch for users is not a good idea as far as these features are considered. We should either do the right thing for all the users or dont do it if we feel users/we as users would not want it,

**Comment by nithinsanjey** [comment]
@uvsankar why do want things to be in 2 commits? Did you mean to say 2 PRs?

**Pull request closed without merging**
